# Generated by Django 2.1.11 on 2019-12-06 06:38

import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaselineModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Baseline Model ID')),
                ('model_class', models.CharField(max_length=512, verbose_name='Model Class')),
                ('data', django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True)),
            ],
        ),
    ]
