# Generated by Django 2.1.15 on 2019-12-20 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_crate_topic_migration'),
        ('eemeter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baselinemodel',
            name='meter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Meter'),
        ),
    ]
