# Generated by Django 2.1.15 on 2019-12-20 02:14

from django.db import migrations
from django.contrib.postgres.fields import JSONField


def set_frequency(apps, schema_editor):
    M = apps.get_model('eemeter', 'baselinemodel')
    for model in M.objects.all().iterator():
        if 'daily' in model.model_class.lower():
            model.frequency = 'daily'
        else:
            model.frequency = 'hourly'
        model.save()


class Migration(migrations.Migration):

    dependencies = [
        ('eemeter', '0003_add_frequency_to_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baselinemodel',
            name='data',
        ),
        migrations.AddField(
            model_name='baselinemodel',
            name='data',
            field=JSONField(blank=True, null=True),
        ),
    ]
