# Generated by Django 2.1.15 on 2019-12-20 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eemeter', '0004_json_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='baselinemodel',
            name='description',
            field=models.CharField(blank=True, null=True, max_length=255),
        ),
        migrations.AddField(
            model_name='baselinemodel',
            name='from_datetime',
            field=models.DateTimeField(blank=True, null=True)
        ),
        migrations.AddField(
            model_name='baselinemodel',
            name='thru_datetime',
            field=models.DateTimeField(blank=True, null=True)
        ),
        migrations.AddField(
            model_name='baselinemodel',
            name='created_datetime',
            field=models.DateTimeField(blank=True, null=True)
        ),
        migrations.AddField(
            model_name='baselinemodel',
            name='last_calc_saving_datetime',
            field=models.DateTimeField(blank=True, null=True)
        ),
        migrations.AddField(
            model_name='baselinemodel',
            name='plot_data',
            field=models.TextField(blank=True, null=True)
        ),
    ]
