# Generated by Django 2.2.13 on 2020-10-16 18:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eemeter', '0007_add_model_params_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baselinemodel',
            name='created_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='baselinemodel',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='baselinemodel',
            name='frequency',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily')], max_length=255, verbose_name='Frequency'),
        ),
        migrations.AlterField(
            model_name='baselinemodel',
            name='from_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='From Date'),
        ),
        migrations.AlterField(
            model_name='baselinemodel',
            name='last_calc_saving_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Calculated Savings Date'),
        ),
        migrations.AlterField(
            model_name='baselinemodel',
            name='thru_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thru Date'),
        ),
        migrations.AlterField(
            model_name='baselinemodel',
            name='uom',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.UnitOfMeasure'),
        ),
    ]
