# Generated by Django 2.0.13 on 2019-06-30 12:24

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_add_topic_tag_rule'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicTagRuleSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.RunSQL('DELETE FROM core_topictagrule;'),
        migrations.RemoveField(
            model_name='topictagrule',
            name='rule_name',
        ),
        migrations.AddField(
            model_name='topictagrule',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='topictagrule',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topictagrule',
            name='rule_set',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.TopicTagRuleSet'),
            preserve_default=False,
        ),
    ]
