# Generated by Django 2.1.10 on 2019-07-17 11:20

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20190716_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='bacnetconfig',
            name='site_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Entity'),
        ),

    ]
