# Generated by Django 2.1.10 on 2019-07-17 12:18

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20190717_0420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bacnetconfig',
            old_name='site_id',
            new_name='site',
        ),

    ]
