# Generated by Django 2.1.10 on 2019-07-30 13:09

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20190717_0518'),
    ]

    operations = [        
        migrations.RunSQL(
            """
            DROP VIEW IF EXISTS core_equipment_view;
            CREATE OR REPLACE VIEW core_equipment_view AS
                SELECT entity_id,
                kv_tags->'id' as object_id,
                kv_tags->'dis' as description,
                kv_tags->'siteRef' as site_id,
                dashboard_uid,
                kv_tags,
                m_tags
                FROM core_entity
                WHERE 'equip' = ANY(m_tags);
            """,
            reverse_sql="""
            DROP VIEW IF EXISTS core_equipment_view;
            CREATE OR REPLACE VIEW core_equipment_view AS
                SELECT entity_id,
                kv_tags->'id' as object_id,
                kv_tags->'dis' as description,
                kv_tags->'siteRef' as site_id,
                kv_tags,
                m_tags
                FROM core_entity
                WHERE 'equip' = ANY(m_tags);
            """
        ),
    ]
