# Generated by Django 2.1.10 on 2019-11-18 16:04

import cratedb.fields.array
import cratedb.fields.hstore
from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20190828_0339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('meter_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Meter ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('from_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='From Date')),
                ('thru_datetime', models.DateTimeField(null=True, verbose_name='Thru Date')),
            ],
        ),
        migrations.AddField(
            model_name='meter',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Entity'),
        ),
    ]
