# Generated by Django 2.1.11 on 2019-11-22 03:05

import cratedb.fields.array
import cratedb.fields.hstore
from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20191121_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherstation',
            name='source',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
