# Generated by Django 2.1.10 on 2019-11-22 15:30

import cratedb.fields.array
import cratedb.fields.hstore
from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20191122_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherstation',
            name='elevation_uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.UnitOfMeasure'),
        ),
    ]
