# Generated by Django 2.1.11 on 2019-11-22 04:21

import cratedb.fields.array
import cratedb.fields.hstore
from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20191121_2128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteweatherstations',
            old_name='site_id',
            new_name='site',
        ),
        migrations.RenameField(
            model_name='siteweatherstations',
            old_name='weather_station_id',
            new_name='weather_station',
        ),
        migrations.RenameField(
            model_name='weatherhistory',
            old_name='weather_station_id',
            new_name='weather_station',
        ),
        migrations.AddField(
            model_name='meter',
            name='weather_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.WeatherStation'),
        ),
    ]
