# Generated by Django 2.1.10 on 2019-11-22 14:21

import cratedb.fields.array
import cratedb.fields.hstore
from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20191121_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('uom_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'core_unit_of_measure',
            },
        ),
    ]
