# Generated by Django 2.1.11 on 2019-11-22 22:18

import cratedb.fields.array
import cratedb.fields.hstore
from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20191121_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='thru_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thru Date'),
        ),
        migrations.AlterField(
            model_name='meter',
            name='weather_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.WeatherStation'),
        ),
    ]
