# Generated by Django 2.1.11 on 2019-11-27 18:11

import cratedb.fields.array
import cratedb.fields.hstore
from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20191122_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherhistory',
            name='weather_history_id',
        ),
        migrations.AddField(
            model_name='weatherhistory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Weather History ID'),
            preserve_default=False,
        ),
    ]
