# Generated by Django 2.1.11 on 2019-12-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20191130_0310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meterhistory',
            name='meter_history_id',
        ),
        migrations.AddField(
            model_name='meterhistory',
            name='meter_history_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Meter History ID'),
            preserve_default=False,
        ),
    ]
