# Generated by Django 2.1.15 on 2019-12-20 13:18

import cratedb.fields.array
import cratedb.fields.hstore
from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_crate_topic_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterhistory',
            name='cost',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='meterhistory',
            name='cost_uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cost_uom', to='core.UnitOfMeasure'),
        ),
        migrations.AddField(
            model_name='meterhistory',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
