# Generated by Django 2.1.15 on 2020-01-03 11:33

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0046_auto_20191220_0518'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterProduction',
            fields=[
                ('meter_production_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Meter Production ID')),
                ('from_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='From Date')),
                ('thru_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Thru Date')),
                ('meter_production_type', models.CharField(max_length=255)),
                ('meter_production_reference', django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True)),
                ('amount', models.FloatField(null=True)),
                ('source', models.CharField(max_length=255)),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Meter')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.UnitOfMeasure')),
            ],
            options={
                'db_table': 'core_meter_production',
            },
        ),
    ]
