# Generated by Django 2.1.15 on 2020-01-09 03:24

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_meter_production'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterproduction',
            name='error_bands',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True),
        ),
    ]
