# Generated by Django 2.2.9 on 2020-01-31 05:20

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_add_error_bands_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOfMeasureConversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='From Date')),
                ('thru_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Thru Date')),
                ('rate', models.FloatField(verbose_name='Rate')),
                ('from_uom', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='conversions_from', to='core.UnitOfMeasure')),
                ('to_uom', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='conversions_to', to='core.UnitOfMeasure')),
            ],
            options={
                'db_table': 'core_unit_of_measure_conversion',
            },
        ),
    ]
