# Generated by Django 2.2.9 on 2020-02-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_tweak_valuation'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitofmeasure',
            name='symbol',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
