# Generated by Django 2.2.9 on 2020-02-05 02:27

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_uom_symbol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meterrateplan',
            name='valuation_method',
        ),
        migrations.AddField(
            model_name='meter',
            name='rate_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.MeterRatePlan'),
        ),
        migrations.DeleteModel(
            name='ValuationMethod',
        ),
    ]
