# Generated by Django 2.2.9 on 2020-02-07 07:30

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0054_financial_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialTransactionNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, verbose_name='Comments')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
                ('financial_transaction', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.FinancialTransaction')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialTransactionFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, verbose_name='Comments')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
                ('can_thumbnail', models.BooleanField(default=False)),
                ('link', models.TextField(blank=True)),
                ('link_name', models.TextField(blank=True)),
                ('financial_transaction', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.FinancialTransaction')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('uploaded_file', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_file', to='filer.File')),
            ],
        ),
    ]
