# This file is part of opentaps Smart Energy Applications Suite (SEAS).

# opentaps Smart Energy Applications Suite (SEAS) is free software:
# you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# opentaps Smart Energy Applications Suite (SEAS) is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.

# You should have received a copy of the GNU Lesser General Public License
# along with opentaps Smart Energy Applications Suite (SEAS).
# If not, see <https://www.gnu.org/licenses/>.


# Generated by Django 2.0.13 on 2019-05-06 14:08

from django.db import migrations, models
from django.db.models.deletion import DO_NOTHING
from django.contrib.postgres.fields import JSONField
from filer.fields.image import FilerImageField


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_add_solaredge_settings_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='SolarEdgeSetting',
            name='site_details',
            field=JSONField(verbose_name="Site Details", blank=True, null=True)
        ),
        migrations.AddField(
            model_name='SolarEdgeSetting',
            name='meter',
            field=models.ForeignKey(on_delete=models.DO_NOTHING, to='core.Meter')
        ),
        migrations.AddField(
            model_name='SolarEdgeSetting',
            name='site_image',
            field=FilerImageField(null=True, blank=True, related_name="solaredge_site_image", on_delete=models.CASCADE)
        ),
        migrations.AddField(
            model_name='SolarEdgeSetting',
            name='site_thumbnail',
            field=FilerImageField(null=True, blank=True, related_name="solaredge_site_thumbnail", on_delete=models.CASCADE)
        ),
        migrations.AddField(
            model_name='Meter',
            name='equipment',
            field=models.ForeignKey(on_delete=DO_NOTHING, blank=True, null=True, to='core.Entity', related_name='equipment_meters')
        ),
    ]
