# Generated by Django 2.2.10 on 2020-03-09 14:22

import cratedb.fields.array
import cratedb.fields.hstore
from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0057_add_sloaredge_details_and_equipment_meter_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterRatePlanHistory',
            fields=[
                ('rate_plan_history_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Rate Plan History ID')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('params', django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True, verbose_name='Parameters')),
                ('from_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='From Date')),
                ('thru_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Thru Date')),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rate_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MeterRatePlan')),
            ],
            options={
                'db_table': 'core_meter_rate_plan_history',
            },
        ),
    ]
