# Generated by Django 2.2.10 on 2020-03-09 16:57

import cratedb.fields.array
import cratedb.fields.hstore
from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_auto_20200309_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterrateplanhistory',
            name='meter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Meter'),
            preserve_default=False,
        ),
    ]
