# Generated by Django 2.2.10 on 2020-04-08 16:07

import cratedb.fields.array
import cratedb.fields.hstore
from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_auto_20200407_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='attributes',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True, verbose_name='Attributes'),
        ),
    ]
