# Generated by Django 2.2.10 on 2020-04-22 10:37

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0062_auto_20200408_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterFinancialValueItem',
            fields=[
                ('meter_value_item_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Meter Value Item ID')),
                ('from_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='From Date')),
                ('thru_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Thru Date')),
                ('amount', models.FloatField(null=True, verbose_name='Amount')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('meter_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MeterFinancialValue')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.UnitOfMeasure')),
            ],
            options={
                'db_table': 'core_meter_financial_value_item',
            },
        ),
    ]
