# Generated by Django 2.2.10 on 2020-09-16 17:25

import cratedb.fields.array
import cratedb.fields.hstore
from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_add_financial_value_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='utility_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Utility'),
        ),
    ]
