# Generated by Django 2.2.10 on 2020-09-17 12:02

import cratedb.fields.array
import cratedb.fields.hstore
from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_auto_20200916_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utility',
            fields=[
                ('utility_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Utility Number')),
                ('utility_name', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=2, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'core_utility',
            },
        ),
        migrations.RemoveField(
            model_name='meter',
            name='utility_number',
        ),
        migrations.AddField(
            model_name='meter',
            name='account_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Account Number'),
        ),
        migrations.AddField(
            model_name='meter',
            name='utility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Utility'),
        ),
    ]
