# Generated by Django 2.2.9 on 2020-02-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('party_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Party ID')),
                ('party_external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
