# Generated by Django 2.2.23 on 2021-11-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_org_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=255, verbose_name="User's Department"),
        ),
        migrations.AddField(
            model_name='user',
            name='vault_token',
            field=models.CharField(blank=True, max_length=255, verbose_name="User's Vault Token"),
        ),
    ]
