# Generated by Django 2.2.23 on 2021-11-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211105_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='web_socket_key',
            field=models.TextField(blank=True, null=True, verbose_name='Web Socket Key'),
        ),
    ]
